### ISSUE TITLE
Can't connect to tls neither authenticate

### ISSUE THREAD

**Issue by kumy** [leeclemens/check_elasticsearch_snapshot#1]
The is actually not easy way to connect to an tls enabled server. There is also no way to perform authentication or point to an elasticsearch instance exported as a subfolder.

**Comment by nohaj** [comment]
Hello,

Thanks for the work.

How do you connect through TLS without specifying the certificates trust chain ?

**Comment by kumy** [comment]
I my case, the certificate is signed by a known CA. It should trust system trust store?

**Comment by nohaj** [comment]
In my case it's self signed certificates =(

I will try to add the certificates in the trust store of the monitoring server. Thank you.
