### ISSUE TITLE
thresholds in seconds do not work as expected

### ISSUE THREAD

**Issue by speech77** [leeclemens/check_elasticsearch_snapshot#3]
Hi,

something like this:
```bash
./check_elasticsearch_snapshot -s localhost -p 9200 -w 3600 -c 36000
```
does not work as expected.
After some tests it seems thresholds are in milliseconds instead of seconds.

Could you please verify?

Thanks in advance.

**Comment by leeclemens** [comment]
Hi @speech77  Thanks for pointing this out! You're right, it is using milliseconds. I added some other suffixes to use (e.g. minute, hour) and updated the README in the debug branch. Feel free to let me know if you see any other issues.

**Comment by speech77** [comment]
Hi @leeclemens ty so much. It works perfectly, thanks for your job!

Issue closed.
Cheers
